Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -9,12 +9,10 @@ variables:
 
 steps:
 
-# Install Terraform
 - task: TerraformInstaller@1
   inputs:
     terraformVersion: '1.5.7'
 
-# Azure + Terraform Execution
 - task: AzureCLI@2
   inputs:
     azureSubscription: 'terraform-sp'
@@ -22,16 +20,21 @@ steps:
     scriptLocation: inlineScript
     inlineScript: |
 
+      set -e   # 🔥 VERY IMPORTANT (stop on error)
+
       export ARM_CLIENT_ID=$servicePrincipalId
       export ARM_CLIENT_SECRET=$servicePrincipalKey
       export ARM_SUBSCRIPTION_ID=$subscriptionId
       export ARM_TENANT_ID=$tenantId
 
-      echo "Running Terraform Init"
+      echo "=== INIT ==="
       terraform init -reconfigure
 
-      echo "Running Terraform Plan"
+      echo "=== PLAN ==="
       terraform plan -var="admin_password=$(ADMIN_PASSWORD)" -out=tfplan
 
-      echo "Running Terraform Apply"
+      echo "Check tfplan file"
+      ls -l
+
+      echo "=== APPLY ==="
       terraform apply -auto-approve tfplan
